### ISSUE TITLE
Allow loading python processors from a git repository in NiFi 2.0

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/nifi-operator#570]
NiFi 2.0 adds support for python processors that can be used in flows.
These can be loaded by simply providing them in a directory on the pod and configuring NiFi to look into this directory.
NiFi also supports hot reloading of these processors out of the box, so this would be a perfect use case for a git-sync sidecar container, like we are using for Airflow already.

```[tasklist]
### Tasks
- [ ] Allow specifying a gitsync sidecar container (potentially with multiple repos)
- [ ] Mount repositories into the pods
- [ ] Configure NiFi to load processors from these mounts
```
