### ISSUE TITLE
Allow configuring NiFi proxy host behaviour

### ISSUE THREAD

**Issue by maltesander** [stackabletech/nifi-operator#604]
As a user I want to access my deployed NiFi. It has an check that it's own hostname is in an allow-list.

We want to support the following two use-cases:

1. Turn the check off. Users need this e.g. when they want to deploy the same config to dev, test and prod and are using LoadBalancers because the IPs are not known in advandce.
2. The user is using an Ingress and knows the NiFi will be reachable at 'nifi.mycorp' and only wants to add this to the allow-list.

We propse the following CRD structure for this:

```yaml
spec:
  clusterConfig:
    hostHeaderCheck:
      allowAll: true # mandatory, defaults to true
      additionalAllowedHosts: # mandatory, defaults to []
        - nifi-dev.mycorp
        - nifi-test.mycorp
        - nifi-prod.mycorp
```

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/docker-images/pull/694
- [x] Decide on the default value (@sbernauer: Disable the check by default, as in our Platform all our tools should try to behave the same way in a default config - no other tool has such a silly check!)
- [ ] https://github.com/stackabletech/nifi-operator/pull/668
```

Related https://github.com/stackabletech/nifi-operator/issues/468

**Comment by lfrancke** [comment]
Can you please include a link to the documentation and can you please also include a snippet that we can include in the release notes later?

**Comment by NickLarsenNZ** [comment]
> Can you please include a link to the documentation and can you please also include a snippet that we can include in the release notes later?

https://docs.stackable.tech/home/stable/nifi/usage_guide/security/#host-header-check
